name: Maven Tests

on:
  push:
    branches:
      - main
      - development
      - feat/testing
  pull_request:
    branches:
      - main
      - development
      - feat/testing

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Maven tests
        run: |
          cd ./api
          mvn clean test
